displayName=Safe Level Ups
author=javlanoob
description=Shows the level up box in the chatbox without the game interrupting you
tags=level,skill,experience,hardcore,ironman
plugins=com.safelevelups.SafeLevelUpsPlugin
build=standard
